# -*- coding: utf-8 -*-
"""OKX 風格霓虹新聞生成器

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtQAQt3m5A9G3ZNWj9yreiE_4p1X9gLA
"""

import streamlit as st
import requests
from datetime import datetime
import base64
from io import BytesIO
from PIL import Image
from rembg import remove

# === 設定頁面 ===
st.set_page_config(
    page_title="霓虹新聞速報生成器",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded"
)

# === 常數與資料 ===
NEON_COLORS = {
    "green": "rgba(74, 222, 128, 1)",
    "purple": "rgba(168, 85, 247, 1)",
    "indigo": "rgba(99, 102, 241, 1)",
    "yellow": "rgba(234, 179, 8, 1)"
}

FOOTER_PRESETS = [
    "週末交易怕滑點？快用 OKX Wallet DEX 聚合，最優匯率一鍵換！",
    "OKX Wallet 支援百條公鏈，跨鏈交易一鍵搞定，省時又省力。",
    "Web3 入口首選 OKX Wallet，安全探索 DeFi 與 NFT 世界。",
    "擔心私鑰遺失？OKX MPC 錢包助你輕鬆管理，資產安全更升級。",
    "OKX Earn 提供多元理財方案，讓閒置資產也能穩健增值。",
    "隨時隨地，OKX App 讓你輕鬆掌握市場脈動，交易快人一步。",
    "OKX Web3 錢包，聚合全網流動性，是你衝土狗的最佳利器。",
    "鏈上交互多留心，不明連結千萬別點擊！",
    "行情波動劇烈，合約開單請務必設置止損。",
    "私鑰助記詞不離身，資產安全自己掌握。",
    "Gas Fee 波動大，建議避開壅塞時段操作。",
    "DEX 交易雖然自由，但也別忘了預留 Gas 費。",
    "DeFi 挖礦高收益伴隨高風險，無常損失要精算。",
    "跨鏈橋選擇多，盡量選擇官方橋樑最穩妥。",
    "迷因幣波動劇烈，投資前請做好功課 (DYOR)。",
    "牛市不言頂，熊市不言底，定期定額最安心。",
    "週末流動性較差，大額交易請注意滑點衝擊。"
]

# === Helper Functions ===

def remove_background(image_data):
    """使用 rembg 移除背景"""
    try:
        input_image = Image.open(BytesIO(image_data))
        output_image = remove(input_image)
        buffered = BytesIO()
        output_image.save(buffered, format="PNG")
        return base64.b64encode(buffered.getvalue()).decode()
    except Exception as e:
        st.error(f"去背失敗: {e}")
        return base64.b64encode(image_data).decode()

def get_coingecko_image(query):
    """搜尋 CoinGecko 並回傳圖片 URL"""
    try:
        url = f"https://api.coingecko.com/api/v3/search?query={query}"
        response = requests.get(url, timeout=5)
        data = response.json()
        if data.get('coins'):
            coin = data['coins'][0]
            return coin.get('large') or coin.get('thumb')
    except Exception as e:
        st.warning(f"CoinGecko API 連線錯誤: {e}")
    return None

def download_image_as_base64(url, do_remove_bg=False):
    """下載圖片並轉為 Base64，可選是否去背"""
    try:
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            if do_remove_bg:
                return remove_background(response.content)
            else:
                return base64.b64encode(response.content).decode()
    except Exception:
        pass
    return None

# === 側邊欄：編輯區 ===
with st.sidebar:
    st.header("⚡ 編輯面板")

    with st.expander("📅 全域設定", expanded=True):
        col1, col2 = st.columns([2, 1])
        main_title = col1.text_input("主標題", "DEX 速報")
        date_str = col2.text_input("日期", datetime.now().strftime("%m/%d"))
        sub_title = st.text_input("副標題", "社群小編獨家整理")

    news_data = []

    # 生成 4 則新聞的輸入框
    for i in range(4):
        with st.expander(f"📰 新聞 #{i+1}", expanded=False):
            title = st.text_input(f"標題 #{i+1}", key=f"title_{i}")
            content = st.text_area(f"內文 #{i+1}", key=f"content_{i}", height=100)

            # 代幣圖片設定
            col_t1, col_t2 = st.columns([3, 1])
            token_query = col_t1.text_input(f"代幣名稱 (例如 BTC) #{i+1}", key=f"token_{i}")
            auto_fetch = col_t2.button("🔍 抓圖", key=f"btn_{i}")

            # 狀態管理 (Session State for image url)
            img_key = f"img_url_{i}"
            if img_key not in st.session_state:
                st.session_state[img_key] = ""

            if auto_fetch and token_query:
                found_url = get_coingecko_image(token_query)
                if found_url:
                    st.session_state[img_key] = found_url
                    st.success("找到圖片！")
                else:
                    st.error("找不到代幣")

            # 顯示/編輯圖片連結
            image_url = st.text_input(f"圖片網址 #{i+1}", value=st.session_state[img_key], key=f"input_url_{i}")

            # 去背選項
            remove_bg_option = st.checkbox("✂️ 自動去背 (AI)", value=True, key=f"bg_{i}")

            # 狀態圖示選擇
            status_icon = st.selectbox(
                f"狀態圖示 #{i+1}",
                ["無", "上漲 (Bull)", "下跌 (Bear)", "警告 (Alert)", "鎖倉 (Lock)", "解鎖 (Unlock)"],
                key=f"status_{i}"
            )

            news_data.append({
                "title": title,
                "content": content,
                "image_url": image_url,
                "remove_bg": remove_bg_option,
                "status": status_icon
            })

    with st.expander("📢 底部跑馬燈", expanded=True):
        selected_preset = st.selectbox("選擇常用金句", ["自訂..."] + FOOTER_PRESETS)
        if selected_preset == "自訂...":
            footer_text = st.text_input("自訂文字", "One More Thing: ...")
        else:
            footer_text = st.text_input("底部文字", selected_preset)

# === 主畫面：生成與預覽 ===

st.title("⚡ 霓虹新聞速報生成器")
st.markdown("填寫左側欄位，右側將即時生成預覽圖。")

if st.button("🚀 生成預覽圖 (Generate)", type="primary"):
    with st.spinner("正在處理圖片與去背中..."):
        # 預先處理圖片 Base64
        processed_news = []
        for idx, item in enumerate(news_data):
            img_b64 = None
            if item["image_url"]:
                img_b64 = download_image_as_base64(item["image_url"], item["remove_bg"])

            # 決定狀態圖示 SVG (簡化版)
            status_svg = ""
            status_color = ""
            if item["status"] != "無":
                if "上漲" in item["status"]:
                    status_color = "text-green-400"
                    status_svg = '<svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline><polyline points="17 6 23 6 23 12"></polyline></svg>'
                elif "下跌" in item["status"]:
                    status_color = "text-red-400"
                    status_svg = '<svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="23 18 13.5 8.5 8.5 13.5 1 6"></polyline><polyline points="17 18 23 18 23 12"></polyline></svg>'
                elif "警告" in item["status"]:
                    status_color = "text-yellow-400"
                    status_svg = '<svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12.01" y2="17"></line></svg>'
                elif "鎖倉" in item["status"]:
                    status_color = "text-purple-400"
                    status_svg = '<svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>'
                elif "解鎖" in item["status"]:
                    status_color = "text-pink-400"
                    status_svg = '<svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 9.9-1"></path></svg>'

            processed_news.append({
                **item,
                "img_b64": f"data:image/png;base64,{img_b64}" if img_b64 else None,
                "status_svg": status_svg,
                "status_color": status_color,
                "border_color": list(NEON_COLORS.keys())[idx]
            })

        # 組合 HTML
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <script src="https://cdn.tailwindcss.com"></script>
            <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@400;700;900&display=swap" rel="stylesheet">
            <style>
                body {{ font-family: 'Noto Sans TC', sans-serif; background: #000; color: white; margin: 0; padding: 20px; }}
                .neon-card {{ background: rgba(17, 24, 39, 0.8); backdrop-filter: blur(10px); }}
                .border-green {{ border: 1px solid {NEON_COLORS['green']}; box-shadow: 0 0 15px rgba(74, 222, 128, 0.15); }}
                .border-purple {{ border: 1px solid {NEON_COLORS['purple']}; box-shadow: 0 0 15px rgba(168, 85, 247, 0.15); }}
                .border-indigo {{ border: 1px solid {NEON_COLORS['indigo']}; box-shadow: 0 0 15px rgba(99, 102, 241, 0.15); }}
                .border-yellow {{ border: 1px solid {NEON_COLORS['yellow']}; box-shadow: 0 0 15px rgba(234, 179, 8, 0.15); }}
                .text-gradient {{ background-clip: text; -webkit-background-clip: text; color: transparent; background-image: linear-gradient(to bottom right, #ffffff, rgba(255,255,255,0.7)); }}
                .glow-text {{ text-shadow: 0 0 10px rgba(74, 222, 128, 0.5); }}
            </style>
        </head>
        <body>
            <div style="width: 800px; height: 800px; background: #000; padding: 32px; position: relative; overflow: hidden; margin: 0 auto;">
                <!-- Top Line -->
                <div style="position: absolute; top: 0; left: 0; width: 100%; height: 4px; background: linear-gradient(90deg, #4ade80, #a855f7, #ec4899);"></div>

                <!-- Header -->
                <div class="flex items-end justify-between mb-6 pb-4 border-b border-gray-800">
                    <div class="flex items-baseline gap-4">
                        <h1 class="text-4xl font-black text-green-400 tracking-tight glow-text">
                            {main_title} <span class="text-white ml-2 text-3xl font-bold">{date_str}</span>
                        </h1>
                        <div class="h-6 w-[1px] bg-gray-600"></div>
                        <h2 class="text-xl text-white font-medium tracking-wide">{sub_title}</h2>
                    </div>
                </div>

                <!-- Grid -->
                <div class="grid grid-cols-2 gap-4">
                    {''.join([f'''
                    <div class="relative neon-card rounded-2xl p-6 border-{item['border_color']} flex flex-col justify-between h-[280px]">
                        <div class="relative z-10">
                            <h3 class="text-3xl font-bold leading-tight mb-4 text-white">
                                {item['title']}
                            </h3>
                            <p class="text-gray-300 text-xl leading-relaxed font-medium">
                                {item['content']}
                            </p>
                        </div>

                        <div class="absolute bottom-4 right-4 z-0">
                             <div class="flex items-end gap-3">
                                {f'<img src="{item["img_b64"]}" class="w-20 h-20 object-contain drop-shadow-lg">' if item['img_b64'] else ''}

                                {f'<div class="{item["status_color"]} opacity-90">{item["status_svg"]}</div>' if item['status_svg'] and not item['img_b64'] else ''}
                             </div>
                        </div>
                    </div>
                    ''' for item in processed_news])}
                </div>

                <!-- Footer -->
                <div class="mt-6 pt-4 border-t border-gray-800">
                    <div class="flex items-center gap-2">
                        <span class="text-green-400 font-bold text-lg whitespace-nowrap">One More Thing:</span>
                        <p class="text-white text-lg font-medium truncate">{footer_text.replace('One More Thing:', '')}</p>
                    </div>
                    <div class="flex justify-between items-center mt-4 text-gray-500 text-sm">
                         <div class="flex items-center gap-2">
                            <div class="bg-white text-black font-black px-2 py-0.5 text-xs rounded-sm">APP</div>
                            <span class="font-bold tracking-widest text-white">GENERATOR</span>
                         </div>
                         <p>以上內容不構成任何投資建議，投資有風險，入市需謹慎。</p>
                         <div class="flex gap-2">
                            <span>🌐</span>
                         </div>
                    </div>
                </div>
            </div>
        </body>
        </html>
        """

        # 顯示結果
        st.components.v1.html(html_content, height=850, scrolling=True)
        st.info("提示：您可以直接對上方預覽圖進行「右鍵 -> 另存圖片」或使用截圖工具保存。")
